### ISSUE TITLE
Update humantime to 2.0.0

### ISSUE THREAD

**Issue by tailhook** [jean-airoldie/humantime-serde#1]
That has better error reporting and removes `unsafe`.

And as we're here, you can also add `#![forbid(unsafe)]` also people like this.

Also what stops you from declaring version 1.0 for this crate?

**Comment by jean-airoldie** [comment]
Will do.

**Comment by jean-airoldie** [comment]
Also, sorry for the delay, I didn't receive github notifications of your issue.

**Comment by jean-airoldie** [comment]
Closed by ca314cfdf8862b8c96a10264f24ccad19ac96ad5. I also published the crate on `crates.io` as `1.0`.
