### ISSUE TITLE
Why not incorporate into humantime?

### ISSUE THREAD

**Issue by tyranron** [jean-airoldie/humantime-serde#3]
Why have 2 crate when we can feature-gate it in `humantime` itself?

ack @jean-airoldie @tailhook

**Comment by tailhook** [comment]
Because additional dependency is considered antipattern in Rust.

Crates that have `serde` as a feature are ones that introduce a new type. So its impossible to implement serde for that type in an external crate. `humantime` don't introduce any new types, so separate crate for serde implementation is as functional as a feature gate.

**Comment by tyranron** [comment]
@tailhook sorry, but still didn't get it)

Let's consider the following:  
`humantime` provides feature-gated `serde` module, disabled by default.

So, when the user doesn't need `serde` capabilities, he doesn't have any extra dependencies using `humantime`.

But, when he wants `serde` caps, he just enables feature and uses it:
```rust
use serde::{Serialize, Deserialize};
use std::time::{Duration, SystemTime};

#[derive(Serialize, Deserialize)]
struct Foo {
    #[serde(with = "humantime")]
    timeout: Duration,
    #[serde(default)]
    #[serde(with = "humantime")]
    time: Option<SystemTime>,
}
```

That's it. It makes the whole a little bit more friendly for newcomers, instead of searching/googling for additional crates to acomplish this.

Where is the antipattern or downside here?

**Comment by jean-airoldie** [comment]
@tyranron You're right that it wouldn't add any dependencies with a feature gate. But its pretty subjective whether or not this would be an improvement. Since @tailhook seems to think its better this way, I'll side with the status quo.
