### ISSUE TITLE
Re-export humantime

### ISSUE THREAD

**Issue by ruslansagitov** [jean-airoldie/humantime-serde#4]
Re-export humantime, please. So I don’t need to depend on `humantime` itself.

`pub use humantime;`

**Comment by jean-airoldie** [comment]
Fair enough. I'll add a reexport module that contains humantime.

**Comment by jean-airoldie** [comment]
Closed by 7a5123bbd04b05cae96342ae1b616bd3241ab542.

You can `use humantime-serde::re::humantime` directly now. I'll publish a new version shortly.
