### ISSUE TITLE
Support for Option<Serde<T>>

### ISSUE THREAD

**Issue by ijackson** [jean-airoldie/humantime-serde#5]
Hi.  In [Arti](https://tpo.pages.torproject.net/core/arti/) we found we wanted to (de)serialise an `Option<Duration>` using `huamntime`.  We added a module `humantime_serde_option` to one of our own crates.

Would you like us to contribute this upstream to your crate?  If so I will prepare a merge request.  I guess the new module (containing `serialize` and `deserialize`, for use with `#[serde(with)]` should be called `humantime_serde::option`?

Thanks for your attention.

**Comment by jean-airoldie** [comment]
I guess that can be done currently via `Option<Serde<Duration>>`, but its not the most elegant solution. If you got something better I would be open to merging of course.

> containing serialize and deserialize, for use with #[serde(with)] should be called humantime_serde::option?

Yeah, that sounds fine to me.
