### ISSUE TITLE
Date and time without time zone

### ISSUE THREAD

**Issue by nearwall** [jean-airoldie/humantime-serde#9]
Hello!
I use `humantime-serde` to work with json and  a bit confused with it behavior with ISO 8601 formatted strings without timezone.
Strings like that: "2022-07-12T12:01:48" are interpreted like UTC time zone.
And I find similar conversion in your  [test](https://github.com/jean-airoldie/humantime-serde/blob/e5a0f8f2f059d93748f3358035d157b5e5f12df3/src/lib.rs#L351).

But [WIkipedia](https://en.wikipedia.org/wiki/ISO_8601) told about such cases: "If no UTC relation information is given with a time representation, the time is assumed to be in local time."
Almost the same on [StackOverflow](https://stackoverflow.com/questions/33114386/datetime-iso-8601-without-timezone-component)

And now I totally confused, which time zone should be used for date +  time without implicit timezone.
I would really appreciate any help with this

**Comment by jean-airoldie** [comment]
This lib is just serde support for humantime, so I can't really change anything about the actual implementation. Your issue should be filed here https://github.com/tailhook/humantime.

The behavior you describe seems to be an acknowledged limitation here: https://github.com/tailhook/humantime/blob/master/src/date.rs#L109.

**Comment by nearwall** [comment]
@jean-airoldie Thanks a lot!
Everything is clear for me
